apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openvpn-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - http:
        paths:
          - path: /openvpn
            backend:
              service:
                name: openvpn
                port:
                  number: 1194
  # ingressClassName: {{ .Values.ingressClass }}
