replicaCount: 1

image:
  repository: ghcr.io/invine/echo
  tag: main

namespace: echo

env:
  logLevel: "debug"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
# ingress:
#   enabled: true
#   annotations:
#     # Add relevant annotations here. For example,
#     # kubernetes.io/ingress.class: your-ingress-class
#   # hosts:
#   #   - host: k8s.evernest.duckdns.org # Replace with your desired hostname
#   #     paths:
#   #       - path: /echo
#   #         backend:
#   #           service: echo-service
#   #           port: service.port
#   host: echo.evercloud.duckdns.org # Replace with your desired hostname
#   path: /
#   backend:
#     service: echo-service
#     port: service.port
