name: "echo-app"

replicaCount: 1

image:
  repository: ghcr.io/invine/echo
  tag: main

namespace: echo

env:
  logLevel: "debug"

service:
  type: ClusterIP
  # annotations:
  #   service.beta.kubernetes.io/oci-load-balancer-shape: flexible
  #   service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: 10
  #   service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: 10
  port: 80
  targetPort: 8080
  ingress:
    ingressClassName: nginx
    host: echo.sample.com
    path: /echo
    backend:
      service: echo-service
    issuer: letsencrypt-staging
# service:
#   type: ClusterIP
#   port: 80
#   targetPort: 8080
# ingress:
#   enabled: true
#   annotations:
#     # Add relevant annotations here. For example,
#     # kubernetes.io/ingress.class: your-ingress-class
#   # hosts:
#   #   - host: k8s.evernest.duckdns.org # Replace with your desired hostname
#   #     paths:
#   #       - path: /echo
#   #         backend:
#   #           service: echo-service
#   #           port: service.port
#   host: echo.evercloud.duckdns.org # Replace with your desired hostname
#   path: /
#   backend:
#     service: echo-service
#     port: service.port
