image:
  repository: public.ecr.aws/j4w0s0n0/echo
  tag: latest

namespace: echo

service:
  port: 8080

ingress:
  enabled: true
  annotations:
    # Add relevant annotations here. For example,
    # kubernetes.io/ingress.class: your-ingress-class
  # hosts:
  #   - host: k8s.evernest.duckdns.org # Replace with your desired hostname
  #     paths:
  #       - path: /echo
  #         backend:
  #           service: echo-service
  #           port: service.port
  host: echo.evercloud.duckdns.org # Replace with your desired hostname
  path: /
  backend:
    service: echo-service
    port: service.port
