name: "echo-app"

replicaCount: 1

image:
  repository: ghcr.io/invine/echo
  tag: main

namespace: echo

env:
  logLevel: "debug"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  ingress:
    ingressClassName: nginx
    host: echo.example.com
    path: /
    backend:
      service: echo-service
    issuer: letsencrypt-staging
backup:
  veleroNamespace: "velero"
  schedule: "0 0 * * *" # Every day
  ttl: "168h0m0s" # 1 hour
  snapshotVolumes: false
