image:
  repository: vaultwarden/server
  tag: latest
namespace: vaultwarden
name: vaultwarden

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  ingress:
    ingressClassName: nginx
    host: vaultwarden.example.com
    path: /
    backend:
      service: vaultwarden
    issuer: letsencrypt-staging
