image: "vaultwarden/server:latest"
namespace: "vaultwarden"

service:
  port: 8081
  targetPort: 80

ingress:
  enabled: true
  annotations:
    # Add relevant annotations here. For example,
    # kubernetes.io/ingress.class: your-ingress-class
  # hosts:
  #   - host: k8s.evernest.duckdns.org # Replace with your desired hostname
  #     paths:
  #       - path: /echo
  #         backend:
  #           service: echo-service
  #           port: service.port
  host: vaultwarden.evercloud.duckdns.org # Replace with your desired hostname
  path: /
