image:
  repository: elswork/openvpn
  tag: latest
namespace: openvpn
name: ovpn

service:
  port: 1194

backup:
  veleroNamespace: "velero"
  schedule: "0 0 * * *" # Every day
  ttl: "168h0m0s" # 1 hour
  snapshotVolumes: false

classStorage: "longhorn"
