apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
              protocol: TCP
              hostPort: 80
          volumeMounts:
            - name: vaultwarden-data
              mountPath: /data/
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
            claimName: vaultwarden-data
