apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/server-snippet: |
    #   location /.well-known/acme-challenge/ {
    #     proxy_pass http://$host$request_uri;
    cert-manager.io/cluster-issuer: {{ .Values.service.ingress.issuer }}
    # acme.cert-manager.io/http01-edit-in-place: "true" # important to merge with existing ingress resource into a single nginx config file
spec:
  ingressClassName: {{ .Values.service.ingress.ingressClassName }}
  tls:
  - hosts:
    - {{ .Values.service.ingress.host }}
    secretName: {{ .Values.name }}-tls
  rules:
  - host: {{ .Values.service.ingress.host }}
    http:
      paths:
      - path: {{ .Values.service.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.service.port }}