apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: vaultwarden
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
