apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: vaultwarden
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
