apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "echo-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "echo-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "echo-app.name" . }}
    spec:
      containers:
      - name: echo-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: LOG_LEVEL
          value: {{ .Values.env.logLevel }}