apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingres
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: echo-service
                port:
                  number: {{ .Values.service.port }}
