apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: echo-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
