apiVersion: v1
kind: Service
metadata:
  name: {{ include "shellinabox.fullname" . }}
  labels:
    app: {{ include "shellinabox.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4200
      protocol: TCP
  selector:
    app: {{ include "shellinabox.name" . }}
